# Pre-commit hooks for GitHub PI Scanner
# Install: pre-commit install
# Run manually: pre-commit run --all-files
repos:
  - repo: local
    hooks:
      # Quick checks (run first)
      - id: go-fmt
        name: Check Go formatting
        entry: bash -c 'if [ -n "$(gofmt -l .)" ]; then echo "Files need formatting:"; gofmt -l .; exit 1; fi'
        language: system
        types: [go]
        
      - id: go-imports
        name: Check Go imports
        entry: bash -c 'command -v goimports >/dev/null 2>&1 && (test -z "$(goimports -l .)" || (echo "Files need import formatting:"; goimports -l .; exit 1)) || echo "goimports not installed, skipping"'
        language: system
        types: [go]

      - id: go-vet
        name: Run go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        types: [go]

      - id: go-mod-tidy
        name: Check go.mod tidiness
        entry: bash -c 'cp go.mod go.mod.bak && cp go.sum go.sum.bak && go mod tidy && if ! cmp -s go.mod go.mod.bak || ! cmp -s go.sum go.sum.bak; then rm go.mod.bak go.sum.bak; echo "go.mod/go.sum not tidy. Run: go mod tidy"; exit 1; else rm go.mod.bak go.sum.bak; fi'
        language: system
        pass_filenames: false

      # Tests (after basic checks pass)
      - id: go-test-short
        name: Run Go tests (short mode)
        entry: go test -short ./...
        language: system
        pass_filenames: false
        types: [go]

      # Security checks (optional, with graceful fallback)
      - id: go-sec
        name: Security scan (gosec)
        entry: bash -c 'command -v gosec >/dev/null 2>&1 && gosec -fmt text -severity medium ./... || echo "gosec not installed, skipping security scan"'
        language: system
        pass_filenames: false
        types: [go]

      - id: go-vulncheck
        name: Vulnerability check
        entry: bash -c 'command -v govulncheck >/dev/null 2>&1 && govulncheck ./... || echo "govulncheck not installed, skipping vulnerability check"'
        language: system
        pass_filenames: false
        types: [go]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.3
    hooks:
      - id: gitleaks